import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    padding: 40,
    color: '#1B2B4B',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  entreprise: {
    flexDirection: 'column',
    gap: 2,
  },
  entrepriseNom: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#1B2B4B',
  },
  entrepriseInfo: {
    fontSize: 8,
    color: '#666',
  },
  documentTitre: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#F97316',
    textAlign: 'right',
  },
  documentRef: {
    fontSize: 10,
    color: '#666',
    textAlign: 'right',
    marginTop: 4,
  },
  sectionTitre: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#F97316',
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 16,
  },
  clientBox: {
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 4,
    marginBottom: 16,
  },
  clientNom: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
  },
  clientInfo: {
    fontSize: 9,
    color: '#666',
    marginTop: 2,
  },
  table: {
    marginTop: 8,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#1B2B4B',
    color: '#fff',
    padding: 6,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
    padding: 6,
    fontSize: 9,
  },
  colDesc: { width: '40%' },
  colQte: { width: '10%', textAlign: 'center' },
  colUnite: { width: '10%', textAlign: 'center' },
  colPU: { width: '15%', textAlign: 'right' },
  colTVA: { width: '10%', textAlign: 'center' },
  colTotal: { width: '15%', textAlign: 'right' },
  totaux: {
    marginTop: 16,
    alignItems: 'flex-end',
  },
  totauxLigne: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 200,
    paddingVertical: 3,
    fontSize: 10,
  },
  totauxTTC: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 200,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#1B2B4B',
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  mentions: {
    marginTop: 30,
    fontSize: 7,
    color: '#999',
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 7,
    color: '#999',
    textAlign: 'center',
    borderTopWidth: 0.5,
    borderTopColor: '#E5E7EB',
    paddingTop: 8,
  },
})
